import = [
    "~/.config/alacritty/themes/github.toml"
]

[env]
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"

[shell]
## In case of having `Git for Windows`
# program = 'C:/Program Files/Git/bin/bash.exe'
program = 'C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 -use-full-path -shell zsh'

[window]
opacity = 0.84
# decorations = "None"

[bell]
duration = 10

### Font(s)
[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = -1
y = 0

# Keyboard bindings

[keyboard]
bindings = [
    { key = "+", mods = "Control", action = "IncreaseFontSize" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },

    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "N", mods = "Alt", action = "ToggleNormalSelection" },

    { key = "L", mods = "Control|Shift", chars = "l" },
    { key = "H", mods = "Control|Shift", chars = "h" },
]

