import = [
    "~/.config/alacritty/themes/github.toml"
]

[env]
# HOME = "C:/Users/'Alex Vergara'" Would be nice for setting up MSYS2 user's home as the same that W2 uses
LC_CTYPE = "en_US.UTF-8"
HOME="/c/Users/'Alex Vergara'"
TERM = "xterm-256color"

[shell]
# program = 'C:/Program Files/Git/bin/bash.exe'
program = 'tmux'
args = ["--login"]
# working_directory = 'C:/Users/"Alex l/code'

[window]
opacity = 0.75
# decorations = "None"

[bell]
duration = 10

### Font(s)

[font]
size = 10

[font.normal]
family = "MonaspiceAr Nerd Font Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

# Keyboard bindings

[keyboard]
bindings = [
    { key = "+", mods = "Control", action = "IncreaseFontSize" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },

    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "N", mods = "Alt", action = "ToggleNormalSelection" },

    { key = "L", mods = "Control|Shift", chars = "l" },
    { key = "R", mods = "Control|Shift", chars = "h" },
]

